STATIC_GCLIB=/usr/local/lib/libgc.a /usr/local/lib/libgmp.a
CFLAGS = -ansi -Wall -Wextra -Werror -pedantic -Wstrict-overflow -fno-strict-aliasing -pedantic-errors -I/usr/local/include $(STATIC_GCLIB)
#COPTS=-I/usr/local/include



all: joy

#joy: joy.c
#	cc $(COPTS) joy.c $(STATIC_GCLIB) -o joy

