
all: joy_to_ast thun printer

joy_to_ast: joy_to_ast.prolog
	gplc --no-top-level joy_to_ast.prolog

thun: thun.prolog
	gplc --no-top-level thun.prolog

printer: printer.prolog
	gplc --no-top-level printer.prolog

