joy_to_ast: joy_to_ast.prolog
	swipl --goal=main --stand_alone=true -o joy_to_ast -c joy_to_ast.prolog

eval_joy_ast: eval_joy_ast.prolog
	swipl --goal=main --stand_alone=true -o eval_joy_ast -c eval_joy_ast.prolog

